FROM python:3.11.0-alpine

WORKDIR /src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN set -eux \
    && apk add --no-cache --virtual .build-deps build-base \
            openssl-dev libffi-dev gcc musl-dev python3-dev \
            postgresql-dev bash \
    && pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt \
    && rm -rf /root/.cache/pip

COPY ./app/ .

EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
